### ISSUE TITLE
urls.W001 warning

### ISSUE THREAD

**Issue by ionescu77** [ionescu77/myWebsite2#14]
Tried to fix this by removing `$` in urls.py

but it breaks the tests, check next time:

```python
# Landing page URLs
    url(r'^$', include('landing.urls', namespace='landing')),
```
```bash
WARNINGS:
?: (urls.W001) Your URL pattern '^$' uses include with a regex ending with a '$'. Remove the dollar from the regex to avoid problems including URLs.
```
```python
# Landing page URLs
    url(r'^$', include('landing.urls', namespace='landing')),
```
will break:

```bash
python3 src/manage.py jenkins blogengine         Website_ionescu77v2    18:05:37
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..Ăsta este textul de test cu ăîșțâ
..<QuerySet [<Post: My test post>]>
post slug: my-test-post
<QuerySet [<Post: My test post>, <Post: My test post>]>
2nd post slug: my-test-post-1
.............FF.FFF..FF
======================================================================
FAIL: test_create_flatpage (blogengine.tests.FlatPageViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/razvansky/Desktop/Projects/Website_ionescu77v2/src/blogengine/tests.py", line 681, in test_create_flatpage
    self.assertTrue(b'About Me' in response.content)
AssertionError: False is not true

======================================================================
FAIL: test_create_notvalid_post_form (blogengine.tests.PostCreateViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/razvansky/Desktop/Projects/Website_ionescu77v2/src/blogengine/tests.py", line 817, in test_create_notvalid_post_form
    self.assertTrue(b'Save' in response.content)
AssertionError: False is not true

======================================================================
FAIL: test_create_post_nonAuth (blogengine.tests.PostCreateViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/razvansky/Desktop/Projects/Website_ionescu77v2/src/blogengine/tests.py", line 743, in test_create_post_nonAuth
    self.assertEqual(response.status_code, 404)
AssertionError: 200 != 404

======================================================================
FAIL: test_create_valid_post_form (blogengine.tests.PostCreateViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/razvansky/Desktop/Projects/Website_ionescu77v2/src/blogengine/tests.py", line 774, in test_create_valid_post_form
    self.assertTrue( curent_year in response.content.decode("utf-8"))
AssertionError: False is not true

======================================================================
FAIL: test_category_page (blogengine.tests.PostViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/razvansky/Desktop/Projects/Website_ionescu77v2/src/blogengine/tests.py", line 600, in test_category_page
    self.assertTrue('no posts found' in response.content.decode('utf-8'))
AssertionError: False is not true

======================================================================
FAIL: test_tag_page (blogengine.tests.PostViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/razvansky/Desktop/Projects/Website_ionescu77v2/src/blogengine/tests.py", line 636, in test_tag_page
    self.assertTrue('no coresponding posts found' in response.content.decode('utf-8'))
AssertionError: False is not true

======================================================================
FAIL: test_sitemap (blogengine.tests.SiteMapTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/razvansky/Desktop/Projects/Website_ionescu77v2/src/blogengine/tests.py", line 727, in test_sitemap
    self.assertTrue(b'my-test-post' in response.content)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 27 tests in 5.659s

FAILED (failures=7)
Destroying test database for alias 'default'...
```

**Comment by ionescu77** [comment]
still happens:

```bash
(tu_ionescu77) [tu_ionescu77@spaceport ~]$ python src/manage.py migrate
System check identified some issues:

WARNINGS:
?: (urls.W001) Your URL pattern '^$' uses include with a regex ending with a '$'. Remove the dollar from the regex to avoid problems including URLs.
Operations to perform:
```

**Comment by ionescu77** [comment]
Won't fix, cause I need to upgrade Django anyway from 1.11 to a newer version.
