### ISSUE TITLE
ERR: Error 500 when using login form

### ISSUE THREAD

**Issue by ionescu77** [ionescu77/myWebsite2#191]
## Errors
Might fix also #3  with Error 3)

### 1) next
```bash
File "/Users/razvansky/myProjects/myWebsite2/src/accounts/views.py" in login_view
  15.     next_page = request.GET['next']

File "/Users/razvansky/myProjects/myWebsite2/lib/python3.8/site-packages/django/utils/datastructures.py" in __getitem__
  80.             raise MultiValueDictKeyError(key)

Exception Type: MultiValueDictKeyError at /mylogin/
Exception Value: 'next'
```

### 2) bool
```python
[ N 2021-03-01 11:30:16.3716 23200/Ta age/Cor/CoreMain.cpp:1147 ]: Checking whether to disconnect long-running connections for process 30974, application /home/tu_ionescu77/ (staging)
App 1234 output: ENV exported...
App 1234 output: Python 3.6.8
App 1234 output: pip 21.0.1 from /home/tu_ionescu77/lib64/python3.6/site-packages/pip (python 3.6)
App 1234 output: [ pid=1234, time=2021-03-01 09:31:11,529 ]: Internal Server Error: /mylogin/
App 1234 output: Traceback (most recent call last):
App 1234 output:   File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
App 1234 output:     response = get_response(request)
App 1234 output:   File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
App 1234 output:     response = self.process_exception_by_middleware(e, request)
App 1234 output:   File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
App 1234 output:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
App 1234 output:   File "/home/tu_ionescu77/src/accounts/views.py", line 31, in login_view
App 1234 output:     print(request.user.is_authenticated())
App 1234 output: TypeError: 'bool' object is not callable
App 1234 output: [ pid=1234, time=2021-03-01 09:32:33,354 ]: Internal Server Error: /mylogin/
App 1234 output: Traceback (most recent call last):
App 1234 output:   File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
App 1234 output:     response = get_response(request)
App 1234 output:   File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
App 1234 output:     response = self.process_exception_by_middleware(e, request)
App 1234 output:   File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
App 1234 output:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
App 1234 output:   File "/home/tu_ionescu77/src/accounts/views.py", line 31, in login_view
App 1234 output:     print(request.user.is_authenticated())
App 1234 output: TypeError: 'bool' object is not callable
```

**Comment by ionescu77** [comment]
## Investigate

### Maybe Django 2.x

- SO
https://stackoverflow.com/questions/63698771/typeerror-bool-object-is-not-callable-in-django

```python
The user.is_verified is returning a boolean value and hence you don't have to use the paranethesis -> ()
```

- GH

> Per that page: "Using User.is_authenticated() and User.is_anonymous() as methods rather than properties is no longer supported."

**Comment by ionescu77** [comment]
Write a test

**Comment by ionescu77** [comment]
https://stackoverflow.com/questions/24322953/django-multivaluedictkeyerror-while-requesting-get-object/24323254#24323254

On first request there is no form data submitted so `request.GET` would not have any data. So doing `request.GET['pub_date_from']` will fail. You shall use `.get()` method

    pub_from = request.GET.get('pub_date_from')
    pub_to = request.GET.get('pub_date_to')

If these keys are not in the dict, will return `None`. So handle the such cases appropriately in your code.

Also, if you want to filter objects for `ListView` add `get_queryset()` method to return filtered queryset as explained here [Dynamic filtering][1]


  [1]: https://docs.djangoproject.com/en/dev/topics/class-based-views/generic-display/#dynamic-filtering

**Comment by ionescu77** [comment]
## Tests
```bash
python src/manage.py jenkins accounts
```

Added testcase in order to reproduce:

```bash
======================================================================
ERROR: test_login (accounts.tests.AccountsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/razvansky/myProjects/myWebsite2/src/accounts/tests.py", line 43, in test_login
    response = self.client.post('/mylogin/', self.credentials, follow=True)
  File "/Users/razvansky/myProjects/myWebsite2/lib/python3.8/site-packages/django/test/client.py", line 543, in post
    response = super().post(path, data=data, content_type=content_type, secure=secure, **extra)
  File "/Users/razvansky/myProjects/myWebsite2/lib/python3.8/site-packages/django/test/client.py", line 356, in post
    return self.generic('POST', path, post_data, content_type,
  File "/Users/razvansky/myProjects/myWebsite2/lib/python3.8/site-packages/django/test/client.py", line 422, in generic
    return self.request(**r)
  File "/Users/razvansky/myProjects/myWebsite2/lib/python3.8/site-packages/django/test/client.py", line 503, in request
    raise exc_value
  File "/Users/razvansky/myProjects/myWebsite2/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/razvansky/myProjects/myWebsite2/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/razvansky/myProjects/myWebsite2/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/razvansky/myProjects/myWebsite2/src/accounts/views.py", line 31, in login_view
    print(request.user.is_authenticated())
TypeError: 'bool' object is not callable
```

**Comment by ionescu77** [comment]
## Observation

Error 3
Redirects are a mess.

After error 1 and 2 are fixed, we get 404 if we directly call form. Due to next being empty
