### ISSUE TITLE
AXES_CACHE problem when running manage.py

### ISSUE THREAD

**Issue by ionescu77** [ionescu77/myWebsite2#64]
Hmmm

```bash
(tu_ionescu77) [tu_ionescu77@spaceport ~]$ python src/manage.py --version
Traceback (most recent call last):
  File "src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/tu_ionescu77/lib64/python3.6/site-packages/axes/apps.py", line 16, in ready
    'django-axes does not work properly with LocMemCache as the default cache backend'
django.core.exceptions.ImproperlyConfigured: django-axes does not work properly with LocMemCache as the default cache backend please add e.g. a DummyCache backend for axes and configure it with AXES_CACHE
```

**Comment by ionescu77** [comment]
As we can see, we have it running with:

```bash
[root@spaceport ionescu77v2]# grep DJANGO bin/activate
export DJANGO_SETTINGS_MODULE="ionescu77v2Project.settings.test"
```

And if we grep inside:
```bash
src/ionescu77v2Project/settings/test.py:AXES_VERBOSE = False
src/ionescu77v2Project/settings/test.py:AXES_LOCKOUT_TEMPLATE = 'lockout.html'
src/ionescu77v2Project/settings/test.py:AXES_CACHE = 'axes_cache'
src/ionescu77v2Project/settings/test.py:AXES_VERBOSE = True
src/ionescu77v2Project/settings/test.py:AXES_LOCKOUT_TEMPLATE = 'lockout.html'
```

And in `settings/test.py` we discover a bunch of settings:

```python
AXES_VERBOSE = False

AXES_LOCKOUT_TEMPLATE = 'lockout.html'

# ///////
# ------- django-axes: CACHES enabled, 20181119
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'axes_cache': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
# ------- #

# ///////
# ------- django-axes: Settings for this:
AXES_CACHE = 'axes_cache'
AXES_VERBOSE = True
AXES_LOCKOUT_TEMPLATE = 'lockout.html'
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ------- #

```

**Comment by ionescu77** [comment]
After we added this to requirements it works

```bash
(tu_ionescu77) [tu_ionescu77@spaceport ~]$ python src/manage.py --version
1.11.28
```
