### ISSUE TITLE
MIGRATE: Loaddata problem

### ISSUE THREAD

**Issue by ionescu77** [ionescu77/myWebsite2#68]
During webfaction data export import

```bash
(tu_ionescu77) [tu_ionescu77@spaceport ~]$ python src/manage.py loaddata /tmp/ionescu77_webfaction.data_exContentTypes.json
System check identified some issues:

WARNINGS:
?: (urls.W001) Your URL pattern '^$' uses include with a regex ending with a '$'. Remove the dollar from the regex to avoid problems including URLs.
Traceback (most recent call last):
  File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/db/models/options.py", line 617, in get_field
    return self.fields_map[field_name]
KeyError: 'trusted'
u ad\u0103ugate, \u0219i \u00eentr-adev\u0103r vedem `unconfined_r`:\r\n```bash\r\n-bash-4.2$ ls -Z 9.6/\r\ndrwx------. postgres postgres system_u:obj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/core/serializers/json.py", line 82, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/core/serializers/python.py", line 129, in Deserializer
    field = Model._meta.get_field(field_name)
  File "/home/tu_ionescu77/lib64/python3.6/site-packages/django/db/models/options.py", line 619, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: AccessAttempt has no field named 'trusted'

During handling of the above exception, another exception occurred:
```

**Comment by ionescu77** [comment]
Needed to remote trusted from fixture:

```json
{
1144   "fields": {
1145     "username": "razvansky",
1146     "http_accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
1147     "get_data": "next=/",
1148     "attempt_time": "2019-01-14T14:11:02.303Z",
1149     "post_data": "username=razvansky\ncsrfmiddlewaretoken=q1PzN3J5PubnGNqe0zFx5kthHHt4SWve",
1150     "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",    1151     "failures_since_start": 0,
1152     "ip_address": "127.0.0.1",
1153     "trusted": true,
1154     "path_info": "/mylogin/"
1155   },
1156   "model": "axes.accessattempt",
1157   "pk": 1
1158 },
```


```json
{
1144   "fields": {
1145     "username": "razvansky",
1146     "http_accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
1147     "get_data": "next=/",
1148     "attempt_time": "2019-01-14T14:11:02.303Z",
1149     "post_data": "username=razvansky\ncsrfmiddlewaretoken=q1PzN3J5PubnGNqe0zFx5kthHHt4SWve",
1150     "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36",    1151     "failures_since_start": 0,
1152     "ip_address": "127.0.0.1",

1154     "path_info": "/mylogin/"
1155   },
1156   "model": "axes.accessattempt",
1157   "pk": 1
1158 },
```

**Comment by ionescu77** [comment]
Then it loaded:

```bash
(tu_ionescu77) [tu_ionescu77@spaceport ~]$ python src/manage.py loaddata /tmp/ionescu77_webfaction.data_exContentTypesv2.json
System check identified some issues:

WARNINGS:
?: (urls.W001) Your URL pattern '^$' uses include with a regex ending with a '$'. Remove the dollar from the regex to avoid problems including URLs.
Installed 203 object(s) from 1 fixture(s)
```
